# Generated by Django 2.1.2 on 2020-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookglass', '0003_auto_20200415_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
