# Generated by Django 2.1.2 on 2020-04-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookglass', '0005_taskreport_task_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_request_id', models.CharField(default='', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookglass.Task')),
            ],
            options={
                'db_table': 'taskdetail',
            },
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='task_request_id',
        ),
        migrations.AddField(
            model_name='taskreport',
            name='detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lookglass.TaskDetail'),
        ),
    ]
