# Generated by Django 2.1.2 on 2020-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookglass', '0006_auto_20200416_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='instaince_id',
            field=models.IntegerField(default=1),
        ),
    ]
