# Generated by Django 2.1.2 on 2020-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookglass', '0007_taskreport_instaince_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='command_host',
            field=models.CharField(default='', max_length=200),
        ),
    ]
