# Generated by Django 2.1.2 on 2019-09-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('chinese_name', models.CharField(default='', max_length=300)),
                ('host_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.CharField(default='system', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('lastupdatedby', models.CharField(default='system', max_length=50)),
                ('lastupdatedtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='isp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.CharField(default='system', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.CharField(default='system', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.CharField(default='system', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='i_isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.isp'),
        ),
        migrations.AddField(
            model_name='instance',
            name='i_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.region'),
        ),
        migrations.AddField(
            model_name='instance',
            name='i_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.status'),
        ),
    ]
