# Generated by Django 2.1.2 on 2019-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='i_vip',
            field=models.BooleanField(default=False),
        ),
    ]
