# Generated by Django 2.1.2 on 2019-09-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190917_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('chinese_name', models.CharField(default='', max_length=300)),
                ('host_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('i_vip', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.CharField(default='system', max_length=50)),
                ('creatd_time', models.DateTimeField(auto_now_add=True)),
                ('lastupdatedby', models.CharField(default='system', max_length=50)),
                ('lastupdatedtime', models.DateTimeField(auto_now_add=True)),
                ('i_isp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.isp')),
                ('i_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.region')),
                ('i_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.status')),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='o_isp',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='o_region',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='o_status',
        ),
        migrations.DeleteModel(
            name='operation',
        ),
    ]
