# Generated by Django 2.1.2 on 2019-09-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190917_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='creatd_time',
            new_name='created_time',
        ),
    ]
