# Generated by Django 2.1.2 on 2019-09-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20190917_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='chinese_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
