# Generated by Django 2.1.2 on 2019-12-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_template'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instance',
            table='instance',
        ),
        migrations.AlterModelTable(
            name='isp',
            table='isp',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
