# Generated by Django 2.1.2 on 2019-12-13 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20191202_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='dns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('sort', models.IntegerField()),
                ('d_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.instance')),
            ],
        ),
        migrations.DeleteModel(
            name='template',
        ),
    ]
