# Generated by Django 2.1.2 on 2020-05-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20191213_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dns',
            name='d_instance',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='i_isp',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='i_region',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='i_status',
        ),
        migrations.DeleteModel(
            name='dns',
        ),
        migrations.DeleteModel(
            name='instance',
        ),
        migrations.DeleteModel(
            name='isp',
        ),
        migrations.DeleteModel(
            name='region',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
